name: Build and deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Site
        uses: docker://longfangsong/site_generator
        with:
          args: -i ./data -o ./build -s ./static -t ./templates
      - run: ls
      - name: Dump docker logs on failure
        uses: jwalton/gh-docker-logs@v1
      - name: Deploy to GHPages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
      - name: Unlock
        uses: longfangsong/acquire-lock-with-issue@beta
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          forceUnlockOnly: true